# Generated by Django 3.1.5 on 2023-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20230228_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_status',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('NEW', 'NEW')], default='PRESENT', max_length=50),
        ),
    ]
